"""``render`` — dataset to Obsidian-visible transcript chunks.

Contract (DESIGN §1, §4; PLAN step 5):

* Read turns through the SDK's ``Dataset.turns(merge_gap_s=…)`` — never a local
  re-implementation. Two turn assemblers that disagree by one merge produce
  evidence links that point at the wrong words. ``drop_bleed`` stays **off**:
  rendering keeps bleed-suspect turns and marks them, because a wrong guess
  deletes real dialogue. Extraction is the stage that drops them.
* Apply lexicon substitution at render time (the dataset stays verbatim), map
  ``user_id`` to a name through ``_speakers.yaml``, and **mark** unmapped
  speakers rather than guessing one.
* Mark bleed and overlap; split chunks on turn boundaries at roughly
  ``--window-minutes``; write ``NN-mmm-mmm.md`` lines shaped
  ``[hh:mm:ss] **Speaker**: text ^t<turnid>`` plus the ``__<id>.md`` overview.
* Write ``anchors.json`` (``segment_i -> {turn_id, chunk, t0}``) — the ID bridge
  every later stage resolves evidence through — and ``index.sqlite`` for ``grep``.
* Snapshot both ``_*.yaml`` into ``inputs/`` so a rendered transcript records the
  identity and correction data it was produced with.
* Skip-if-done on ``CompositeKey(dataset_digest, lexicon_digest, speakers_digest,
  knobs={window_minutes, merge_gap_s})``.

Two decisions worth stating where the code lives.

**Substitution is exact replacement of enumerated strings, never matching.** For
every active lexicon term, each string the owner wrote down in ``variants`` is
replaced by ``display_ru`` (or ``canonical``). One alternation regex is built
from all of them, longest first, so ``Вазагар`` cannot be clobbered by a shorter
variant nested inside it, and a replacement can never be re-matched by a later
pass. Word boundaries are Unicode ``\\w`` lookarounds, which are correct for
Cyrillic. There is deliberately no similarity, distance or fuzzy logic anywhere
in this file.

A ``morph: true`` term adds *more enumerated strings* to that same alternation —
case-paired forms generated by :mod:`session_ingest.morphs`, where both the
matched variant and its replacement were inflected to the same case, so
«Марвике» becomes «Морвике» and not «Морвика». The owner's literal entries are
inserted first and win every conflict, and the two kinds are counted separately
in the ``--json`` payload and in provenance so a substitution can always be
traced back to a line in ``_lexicon.yaml`` or to an auditable generated pair.

**The whole vault directory is rewritten atomically.** Chunk boundaries move when
``--window-minutes`` changes, so an in-place rewrite would leave chunks from the
previous layout lying beside the new ones — stale files that qmd would happily
index and an agent would happily cite. The new tree is staged in a sibling
directory and swapped in.
"""

from __future__ import annotations

import os
import re
import shutil
import sqlite3
from collections.abc import Iterable, Mapping, Sequence
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import yaml
from craig_stt_dataset import Dataset, Segment, Turn

from .adopt import load_session_link, resolve_active_dataset
from .config import SessionConfig
from .models import RecordingLink
from .morphs import ExpansionTable, expand_terms
from .nextsteps import next_steps_for
from .paths import Roots, SessionTree
from .provenance import CompositeKey, Provenance, utc_now
from .qa import count_term
from .vaultfiles import Lexicon, Speakers, load_lexicon, load_speakers
from .writer import read_json, write_json, write_text

#: Marker appended to a turn the SDK flagged as probable cross-track leakage.
BLEED_MARKER = "*(возможный блид с трека {track})*"
BLEED_MARKER_UNKNOWN = "*(возможный блид)*"
OVERLAP_MARKER = "*(наложение: {tracks})*"
UNMAPPED_DISPLAY = "⚠ {name} (не сопоставлен)"

#: Frontmatter ``type`` values, so a qmd/Obsidian query can tell the two apart.
CHUNK_TYPE = "transcript"
OVERVIEW_TYPE = "transcript-overview"


def hhmmss(seconds: float) -> str:
    """``hh:mm:ss`` from a float offset. Truncating, never rounding up past a turn."""
    total = max(0, int(seconds))
    return f"{total // 3600:02d}:{(total % 3600) // 60:02d}:{total % 60:02d}"


def hhmm(seconds: float) -> str:
    total = max(0, int(seconds))
    return f"{total // 3600:02d}:{(total % 3600) // 60:02d}"


# --------------------------------------------------------------- substitution


#: How a substitution was authorised, for the split counts.
EXPLICIT = "explicit"
GENERATED = "generated"


@dataclass(frozen=True, slots=True)
class SubstitutionCounts:
    """Replacements made, split by whether the owner or the analyzer enumerated them."""

    explicit: dict[str, int] = field(default_factory=dict)
    generated: dict[str, int] = field(default_factory=dict)

    @property
    def total(self) -> int:
        return sum(self.explicit.values()) + sum(self.generated.values())

    def record(self, origin: str, term_id: str) -> None:
        bucket = self.generated if origin == GENERATED else self.explicit
        bucket[term_id] = bucket.get(term_id, 0) + 1

    def to_dict(self) -> dict[str, Any]:
        return {
            "explicit": dict(sorted(self.explicit.items())),
            "generated": dict(sorted(self.generated.items())),
            "total": self.total,
        }


@dataclass(frozen=True, slots=True)
class Substituter:
    """Exact, case-insensitive replacement of enumerated lexicon variants."""

    pattern: re.Pattern[str] | None
    by_variant: Mapping[str, tuple[str, str, str]]

    def apply(self, text: str, counts: SubstitutionCounts) -> str:
        if self.pattern is None or not text:
            return text

        def _replace(match: re.Match[str]) -> str:
            entry = self.by_variant.get(match.group(0).casefold())
            if entry is None:  # pragma: no cover - the pattern is built from the keys
                return match.group(0)
            term_id, replacement, origin = entry
            counts.record(origin, term_id)
            return replacement

        return self.pattern.sub(_replace, text)


def build_substituter(lexicon: Lexicon, expansion: ExpansionTable | None = None) -> Substituter:
    """One alternation over every active term's enumerated variants, longest first.

    Longest-first matters twice: a longer variant containing a shorter one must
    win, and a single pass means a substituted name can never be re-matched by
    another term's variant. Two terms enumerating the same string is a lexicon
    bug the owner has to resolve; the first term in file order wins, so the
    output stays deterministic rather than depending on dict iteration.

    Generated pairs are inserted after every literal one, so an explicit entry
    always wins a conflict with a form the analyzer produced — which is the whole
    reason the owner is allowed to keep hand-written oblique entries beside
    ``morph: true``.
    """
    by_variant: dict[str, tuple[str, str, str]] = {}
    for term in lexicon.active_terms():
        replacement = term.display_ru or term.canonical
        for variant in term.variant_forms():
            key = variant.casefold()
            if key in by_variant:
                continue
            by_variant[key] = (term.id, replacement, EXPLICIT)
    if expansion is not None:
        active = {term.id for term in lexicon.active_terms()}
        for term_id, pair in expansion.iter_pairs():
            if term_id not in active:
                continue
            key = pair.variant.casefold()
            if key in by_variant:
                continue
            by_variant[key] = (term_id, pair.display, GENERATED)
    if not by_variant:
        return Substituter(None, {})
    alternatives = sorted(by_variant, key=lambda value: (-len(value), value))
    pattern = re.compile(
        r"(?<!\w)(?:" + "|".join(re.escape(value) for value in alternatives) + r")(?!\w)",
        re.IGNORECASE,
    )
    return Substituter(pattern, by_variant)


def search_terms_for(
    text: str, lexicon: Lexicon, expansion: ExpansionTable | None = None
) -> list[str]:
    """Mixed-script search aids for terms whose enumerated strings occur in ``text``.

    Both the Russian display form and the canonical form are emitted, so a note
    written in either script finds the chunk. Occurrence is exact counting over
    enumerated strings — the same rule ``qa`` measures the miss rate with, so a
    chunk where only an inflected form was said is still found under the lemma.
    """
    if not lexicon.present:
        return []
    haystack = text.casefold()
    found: list[str] = []
    for term in lexicon.active_terms():
        if count_term(haystack, term, expansion).total_hits == 0:
            continue
        for form in (term.display_ru or term.canonical, term.canonical):
            if form and form not in found:
                found.append(form)
    return found


# ------------------------------------------------------------------- speakers


def speaker_display(
    *, user_id: str | None, username: str | None, track: int, speakers: Speakers
) -> tuple[str, bool]:
    """``(display, mapped)``. An unmapped id is marked, never guessed at."""
    mapped = speakers.get(user_id)
    if mapped is not None:
        return (mapped.character or mapped.player or username or mapped.user_id), True
    return UNMAPPED_DISPLAY.format(name=username or user_id or f"track {track}"), False


# -------------------------------------------------------------------- chunking


@dataclass(slots=True)
class RenderedTurn:
    """One turn, with everything the line needs already resolved."""

    turn: Turn
    speaker: str
    mapped: bool
    text: str
    bleed_track: int | None

    def line(self) -> str:
        parts = [f"- [{hhmmss(self.turn.t0)}] **{self.speaker}**: {self.text}"]
        if self.turn.overlap:
            parts.append(
                " " + OVERLAP_MARKER.format(tracks=",".join(str(t) for t in self.turn.overlap))
            )
        if self.turn.bleed_suspect:
            parts.append(
                " "
                + (
                    BLEED_MARKER.format(track=self.bleed_track)
                    if self.bleed_track is not None
                    else BLEED_MARKER_UNKNOWN
                )
            )
        parts.append(f" ^{self.turn.id}")
        return "".join(parts)


@dataclass(slots=True)
class Chunk:
    """One ``NN-mmm-mmm.md`` file: a whole number of turns, never a split one."""

    index: int
    window: int
    window_minutes: int
    turns: list[RenderedTurn] = field(default_factory=list)

    @property
    def start_minute(self) -> int:
        return self.window * self.window_minutes

    @property
    def end_minute(self) -> int:
        return self.start_minute + self.window_minutes

    @property
    def name(self) -> str:
        return f"{self.index:02d}-{self.start_minute:03d}-{self.end_minute:03d}"

    @property
    def filename(self) -> str:
        return f"{self.name}.md"

    @property
    def t0(self) -> float:
        return self.turns[0].turn.t0

    @property
    def t1(self) -> float:
        return max(entry.turn.t1 for entry in self.turns)


def chunk_turns(turns: Sequence[RenderedTurn], *, window_minutes: int) -> list[Chunk]:
    """Group turns into fixed windows, assigned by the turn's **start** time.

    Assignment by ``t0`` is what puts every boundary on a turn boundary: a turn
    that straddles a window edge belongs entirely to the window it began in, so
    no chunk ever contains half a sentence and no line appears twice.

    A window nobody spoke in produces no file, so the ``NN`` ordinal counts
    emitted chunks while the ``mmm-mmm`` minutes name the window — they coincide
    on a session with no long silences and diverge honestly on one that has them.
    """
    window_s = float(window_minutes * 60)
    chunks: list[Chunk] = []
    for entry in turns:
        window = int(entry.turn.t0 // window_s)
        if not chunks or chunks[-1].window != window:
            chunks.append(
                Chunk(index=len(chunks) + 1, window=window, window_minutes=window_minutes)
            )
        chunks[-1].turns.append(entry)
    return chunks


# --------------------------------------------------------------- file bodies


def _frontmatter(payload: Mapping[str, Any]) -> str:
    body = yaml.safe_dump(
        dict(payload), allow_unicode=True, sort_keys=False, default_flow_style=False
    )
    return f"---\n{body}---\n"


def chunk_document(
    chunk: Chunk,
    *,
    session_id: str,
    lexicon: Lexicon,
    verbatim_text: str,
    expansion: ExpansionTable | None = None,
) -> str:
    """Frontmatter plus one line per turn. The line format is stable by contract."""
    speakers_present: list[str] = []
    for entry in chunk.turns:
        if entry.speaker not in speakers_present:
            speakers_present.append(entry.speaker)
    front = _frontmatter(
        {
            "session": session_id,
            "type": CHUNK_TYPE,
            "chunk": chunk.name,
            "chunk_index": chunk.index,
            "t0": round(chunk.t0, 3),
            "t1": round(chunk.t1, 3),
            "turns": len(chunk.turns),
            "speakers": speakers_present,
            "search_terms": search_terms_for(verbatim_text, lexicon, expansion),
        }
    )
    lines = [entry.line() for entry in chunk.turns]
    return front + "\n" + "\n".join(lines) + "\n"


def _participants_table(dataset: Dataset, speakers: Speakers) -> list[str]:
    rows = [
        "| Участник | Discord | Речь | Доля |",
        "|---|---|---:|---:|",
    ]
    total = sum(info.speech_s for info in dataset.speakers() if not info.skipped)
    for info in dataset.speakers():
        # A deliberately excluded track (an ignored bot) is not a participant the
        # owner forgot to map, so it is listed without the unmapped warning.
        if info.skipped:
            display = f"{info.username or info.user_id or f'track {info.track}'} (пропущен)"
        else:
            display, _ = speaker_display(
                user_id=info.user_id, username=info.username, track=info.track, speakers=speakers
            )
        share = (info.speech_s / total) if total else 0.0
        rows.append(
            f"| {display} | {info.username or info.user_id or '—'} | "
            f"{hhmmss(info.speech_s)} | {share:.0%} |"
        )
    return rows


def _qa_one_liner(tree: SessionTree) -> str | None:
    """The QA headline, if ``qa`` has run. Absence is normal, not an error."""
    if not tree.qa_json.is_file():
        return None
    try:
        payload = read_json(tree.qa_json)
    except (OSError, ValueError):
        return None
    if not isinstance(payload, dict):
        return None
    raw_metrics = payload.get("metrics")
    metrics: dict[str, Any] = raw_metrics if isinstance(raw_metrics, dict) else {}
    crossed = payload.get("thresholds_crossed") or []
    parts: list[str] = []
    for key in ("word_p10", "bleed_rate", "lexicon_miss_rate"):
        value = metrics.get(key)
        parts.append(f"{key}={value:.3g}" if isinstance(value, (int, float)) else f"{key}=n/a")
    names = ", ".join(str(entry.get("metric")) for entry in crossed if isinstance(entry, dict))
    parts.append(f"порогов пересечено: {len(crossed)}" + (f" ({names})" if names else ""))
    return " · ".join(parts)


def overview_document(
    *,
    tree: SessionTree,
    dataset: Dataset,
    recording: RecordingLink,
    speakers: Speakers,
    chunks: Sequence[Chunk],
    window_minutes: int,
    merge_gap_s: float,
    segments: int,
    turns: int,
    unmapped: Sequence[Mapping[str, Any]],
) -> str:
    meta = dataset.meta
    front = _frontmatter(
        {
            "session": tree.id,
            "type": OVERVIEW_TYPE,
            "recording_id": recording.recording_id,
            "dataset_digest": recording.dataset_digest,
            "started_at": recording.started_at,
            "duration_s": meta.recording.duration_s,
            "language": meta.provenance.language,
            "stt_model": meta.provenance.model,
            "window_minutes": window_minutes,
            "merge_gap_s": merge_gap_s,
            "chunks": len(chunks),
            "turns": turns,
            "segments": segments,
            "generated": utc_now(),
        }
    )
    body: list[str] = [
        f"# Транскрипт сессии {tree.id}",
        "",
        "> [!warning] Машинная расшифровка",
        "> Дословная запись сказанного за столом, а не канон кампании. "
        "Цитировать можно, делать из этого истину — нет.",
        "",
        "## Участники",
        "",
        *_participants_table(dataset, speakers),
        "",
    ]
    if unmapped:
        body.extend(
            [
                "> [!todo] Не сопоставленные участники",
                "> "
                + ", ".join(
                    f"`{entry.get('user_id')}` ({entry.get('username') or 'без имени'})"
                    for entry in unmapped
                )
                + " — добавьте их в `vault/transcripts/_speakers.yaml` и перерендерите.",
                "",
            ]
        )
    body.extend(["## Чанки", ""])
    for chunk in chunks:
        body.append(
            f"- [[transcripts/{tree.id}/{chunk.name}|{hhmm(chunk.t0)}–{hhmm(chunk.t1)}]] "
            f"— {len(chunk.turns)} реплик"
        )
    body.append("")
    qa_line = _qa_one_liner(tree)
    body.extend(["## Качество", "", qa_line or "`qa` ещё не запускался для этой сессии.", ""])
    body.extend(
        [
            "## Пересказ",
            "",
            f"- Черновик: `{tree.recap_draft}` — создаётся `session-ingest recap`.",
            f"- Структурированная запись: `{tree.record_json}` — создаётся `session-ingest record`.",
            "- Хроника сессии живёт в `vault/notes/sessions/`; её пишет агент, не этот CLI.",
            "",
        ]
    )
    return front + "\n" + "\n".join(body)


# ------------------------------------------------------------------- sqlite


_SCHEMA = """
CREATE TABLE meta (key TEXT PRIMARY KEY, value TEXT);
CREATE TABLE segments (
    i INTEGER PRIMARY KEY,
    t0 REAL NOT NULL,
    t1 REAL NOT NULL,
    track INTEGER NOT NULL,
    user_id TEXT,
    username TEXT,
    speaker TEXT NOT NULL,
    text TEXT NOT NULL,
    text_raw TEXT NOT NULL,
    bleed_suspect INTEGER NOT NULL,
    turn_id TEXT,
    chunk TEXT
);
CREATE INDEX segments_t0 ON segments(t0);
CREATE TABLE turns (
    n INTEGER PRIMARY KEY,
    turn_id TEXT NOT NULL UNIQUE,
    t0 REAL NOT NULL,
    t1 REAL NOT NULL,
    track INTEGER NOT NULL,
    user_id TEXT,
    username TEXT,
    speaker TEXT NOT NULL,
    chunk TEXT NOT NULL,
    text TEXT NOT NULL,
    bleed_suspect INTEGER NOT NULL
);
CREATE INDEX turns_t0 ON turns(t0);
CREATE VIRTUAL TABLE segments_fts USING fts5(text, content='segments', content_rowid='i');
CREATE VIRTUAL TABLE turns_fts USING fts5(text, content='turns', content_rowid='n');
"""


def write_index(
    path: Path,
    *,
    session_id: str,
    dataset_digest: str | None,
    window_minutes: int,
    merge_gap_s: float,
    segment_rows: Sequence[tuple[Any, ...]],
    turn_rows: Sequence[tuple[Any, ...]],
) -> Path:
    """Build ``index.sqlite`` off to the side and swap it in.

    Disposable by design — ``render`` rebuilds it — but a half-written index that
    ``grep`` reads would answer questions wrongly rather than loudly, so it is
    still written atomically.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    staged = path.with_name(path.name + ".part")
    staged.unlink(missing_ok=True)
    connection = sqlite3.connect(staged)
    try:
        connection.executescript(_SCHEMA)
        connection.executemany(
            "INSERT INTO segments (i, t0, t1, track, user_id, username, speaker, text, "
            "text_raw, bleed_suspect, turn_id, chunk) "
            "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
            segment_rows,
        )
        connection.executemany(
            "INSERT INTO turns (n, turn_id, t0, t1, track, user_id, username, speaker, chunk, "
            "text, bleed_suspect) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
            turn_rows,
        )
        connection.execute("INSERT INTO segments_fts (rowid, text) SELECT i, text FROM segments")
        connection.execute("INSERT INTO turns_fts (rowid, text) SELECT n, text FROM turns")
        connection.executemany(
            "INSERT INTO meta (key, value) VALUES (?, ?)",
            [
                ("session", session_id),
                ("dataset_digest", dataset_digest or ""),
                ("window_minutes", str(window_minutes)),
                ("merge_gap_s", str(merge_gap_s)),
                ("generated_at", utc_now()),
                ("segments", str(len(segment_rows))),
                ("turns", str(len(turn_rows))),
            ],
        )
        connection.commit()
    finally:
        connection.close()
    os.replace(staged, path)
    return path


# ---------------------------------------------------------------- vault swap


def swap_directory(target: Path, staged: Path) -> None:
    """Replace ``target`` with ``staged`` without ever leaving a half-tree behind."""
    target.parent.mkdir(parents=True, exist_ok=True)
    # Dot-prefixed so a crash mid-swap leaves nothing Obsidian shows or qmd indexes.
    backup = target.with_name(f".{target.name}.old")
    if backup.exists():
        shutil.rmtree(backup)
    had_previous = target.exists()
    if had_previous:
        os.replace(target, backup)
    try:
        os.replace(staged, target)
    except OSError:
        if had_previous:
            os.replace(backup, target)
        raise
    if backup.exists():
        shutil.rmtree(backup)


def snapshot(source: Path, destination: Path, *, label: str) -> bool:
    """Copy a hand-maintained vault file into ``inputs/``; record absence honestly."""
    if source.is_file():
        write_text(destination, source.read_text(encoding="utf-8"))
        return True
    write_text(destination, f"# {label} was absent at render time ({utc_now()})\n")
    return False


# ----------------------------------------------------------------- the verb


def _bleed_tracks(segments: Iterable[Segment]) -> dict[int, int | None]:
    return {
        segment.i: segment.bleed.louder_track
        for segment in segments
        if segment.bleed is not None and segment.bleed.suspect
    }


def _normalise(text: str) -> str:
    """One line, single-spaced — so the rendered line format cannot drift."""
    return " ".join(text.split())


def _existing_chunks(directory: Path) -> list[str]:
    if not directory.is_dir():
        return []
    return sorted(p.name for p in directory.glob("*.md") if not p.name.startswith("__"))


def run(
    *,
    roots: Roots,
    config: SessionConfig,
    session_id: str,
    run: int | None = None,
    window_minutes: int | None = None,
    merge_gap_s: float | None = None,
    force: bool = False,
) -> dict[str, Any]:
    """Returns the ``--json`` payload: chunk paths, turn/chunk counts, anchors path."""
    tree = roots.session(session_id)
    recording, dataset = resolve_active_dataset(tree, run)
    link = load_session_link(tree)
    effective_run = run if run is not None else link.active_run

    effective_window = window_minutes if window_minutes is not None else config.window_minutes
    effective_gap = merge_gap_s if merge_gap_s is not None else config.merge_gap_s

    lexicon = load_lexicon(roots.lexicon_file)
    speakers = load_speakers(roots.speakers_file)
    expansion = expand_terms(lexicon)

    key = CompositeKey(
        dataset_digest=recording.dataset_digest,
        lexicon_digest=lexicon.digest,
        speakers_digest=speakers.digest,
        knobs={
            "window_minutes": effective_window,
            "merge_gap_s": effective_gap,
            "run": effective_run,
            # The expansion digest folds in the pymorphy3 and dictionary versions,
            # so upgrading either re-renders rather than leaving chunks corrected
            # by grammar tables the tool no longer ships.
            "morph_digest": expansion.digest(),
        },
    )
    provenance = Provenance.load(tree.provenance_json)
    if provenance.should_skip("render", key, force=force, root=tree.root):
        chunk_names = _existing_chunks(tree.transcript_dir)
        return {
            "status": "skipped",
            "session": session_id,
            "run": effective_run,
            "dataset_digest": recording.dataset_digest,
            "transcript_dir": str(tree.transcript_dir),
            "overview": str(tree.transcript_overview),
            "chunk_count": len(chunk_names),
            "chunks": [{"chunk": Path(name).stem, "file": name} for name in chunk_names],
            "anchors": str(tree.anchors_json),
            "index": str(tree.index_sqlite),
            "window_minutes": effective_window,
            "merge_gap_s": effective_gap,
            "warnings": [
                "already rendered for this dataset/lexicon/speakers key; --force to rewrite"
            ],
            "lines": [f"skipped: {session_id} already rendered ({len(chunk_names)} chunks)"],
            "next_steps": next_steps_for(
                "render", session_id=session_id, api_key_present=config.api_key_present
            ),
        }

    # --- read the dataset once ------------------------------------------------
    segments = list(dataset.iter_segments())
    bleed_tracks = _bleed_tracks(segments)
    substituter = build_substituter(lexicon, expansion)
    substitutions = SubstitutionCounts()

    rendered: list[RenderedTurn] = []
    unmapped: list[dict[str, Any]] = []
    seen_unmapped: set[str] = set()
    for turn in dataset.turns(merge_gap_s=effective_gap, drop_bleed=False):
        display, mapped = speaker_display(
            user_id=turn.user_id, username=turn.username, track=turn.track, speakers=speakers
        )
        if not mapped and turn.user_id is not None and turn.user_id not in seen_unmapped:
            seen_unmapped.add(turn.user_id)
            unmapped.append(
                {"user_id": turn.user_id, "username": turn.username, "track": turn.track}
            )
        bleed_track: int | None = None
        if turn.bleed_suspect:
            for index in turn.segment_indices:
                bleed_track = bleed_tracks.get(index)
                if bleed_track is not None:
                    break
        rendered.append(
            RenderedTurn(
                turn=turn,
                speaker=display,
                mapped=mapped,
                text=_normalise(substituter.apply(turn.text, substitutions)),
                bleed_track=bleed_track,
            )
        )

    chunks = chunk_turns(rendered, window_minutes=effective_window)

    # --- the ID bridge --------------------------------------------------------
    chunk_of_turn: dict[str, str] = {}
    anchors: dict[str, dict[str, Any]] = {}
    segment_chunk: dict[int, tuple[str, str]] = {}
    for chunk in chunks:
        for entry in chunk.turns:
            chunk_of_turn[entry.turn.id] = chunk.name
            for index in entry.turn.segment_indices:
                segment_chunk[index] = (entry.turn.id, chunk.name)
    for segment in segments:
        placed = segment_chunk.get(segment.i)
        if placed is None:
            continue
        turn_id, chunk_name = placed
        anchors[str(segment.i)] = {
            "turn_id": turn_id,
            "chunk": chunk_name,
            "t0": segment.t0,
        }

    warnings: list[str] = []
    unanchored = [segment.i for segment in segments if segment.i not in segment_chunk]
    if unanchored:
        warnings.append(
            f"{len(unanchored)} segment(s) carry no text and therefore no turn, so they have no "
            f"anchor: {unanchored[:10]}"
        )
    if not lexicon.present:
        warnings.append(f"{roots.lexicon_file} is absent — no lexicon substitution was applied")
    if not speakers.present:
        warnings.append(f"{roots.speakers_file} is absent — every speaker is marked unmapped")
    if unmapped:
        warnings.append(
            f"{len(unmapped)} speaking discord id(s) have no _speakers.yaml entry and are marked "
            f"in the transcript"
        )

    # --- write the vault tree atomically -------------------------------------
    target = tree.transcript_dir
    staged = target.with_name(f".{target.name}.part")
    if staged.exists():
        shutil.rmtree(staged)
    staged.mkdir(parents=True)

    verbatim_by_chunk: dict[str, str] = {}
    for chunk in chunks:
        indices = {i for entry in chunk.turns for i in entry.turn.segment_indices}
        verbatim_by_chunk[chunk.name] = "\n".join(
            segment.text for segment in segments if segment.i in indices and segment.text
        )
    for chunk in chunks:
        (staged / chunk.filename).write_text(
            chunk_document(
                chunk,
                session_id=session_id,
                lexicon=lexicon,
                verbatim_text=verbatim_by_chunk[chunk.name],
                expansion=expansion,
            ),
            encoding="utf-8",
        )
    (staged / f"__{session_id}.md").write_text(
        overview_document(
            tree=tree,
            dataset=dataset,
            recording=recording,
            speakers=speakers,
            chunks=chunks,
            window_minutes=effective_window,
            merge_gap_s=effective_gap,
            segments=len(segments),
            turns=len(rendered),
            unmapped=unmapped,
        ),
        encoding="utf-8",
    )
    swap_directory(target, staged)

    # --- sidecars -------------------------------------------------------------
    write_json(tree.anchors_json, anchors)

    speaker_by_segment: dict[int, str] = {}
    for entry in rendered:
        for index in entry.turn.segment_indices:
            speaker_by_segment[index] = entry.speaker
    segment_rows = [
        (
            segment.i,
            segment.t0,
            segment.t1,
            segment.track,
            segment.user_id,
            segment.username,
            speaker_by_segment.get(
                segment.i,
                speaker_display(
                    user_id=segment.user_id,
                    username=segment.username,
                    track=segment.track,
                    speakers=speakers,
                )[0],
            ),
            _normalise(substituter.apply(segment.text, SubstitutionCounts())),
            segment.text,
            1 if (segment.bleed is not None and segment.bleed.suspect) else 0,
            segment_chunk.get(segment.i, (None, None))[0],
            segment_chunk.get(segment.i, (None, None))[1],
        )
        for segment in segments
    ]
    turn_rows = [
        (
            number,
            entry.turn.id,
            entry.turn.t0,
            entry.turn.t1,
            entry.turn.track,
            entry.turn.user_id,
            entry.turn.username,
            entry.speaker,
            chunk_of_turn[entry.turn.id],
            entry.text,
            1 if entry.turn.bleed_suspect else 0,
        )
        for number, entry in enumerate(rendered, start=1)
    ]
    write_index(
        tree.index_sqlite,
        session_id=session_id,
        dataset_digest=recording.dataset_digest,
        window_minutes=effective_window,
        merge_gap_s=effective_gap,
        segment_rows=segment_rows,
        turn_rows=turn_rows,
    )

    speakers_present = snapshot(roots.speakers_file, tree.speakers_snapshot, label="_speakers.yaml")
    lexicon_present = snapshot(roots.lexicon_file, tree.lexicon_snapshot, label="_lexicon.yaml")

    chunk_payload = [
        {
            "chunk": chunk.name,
            "file": str(target / chunk.filename),
            "index": chunk.index,
            "t0": chunk.t0,
            "t1": chunk.t1,
            "turns": len(chunk.turns),
        }
        for chunk in chunks
    ]

    provenance.mark_done(
        "render",
        key,
        outputs=[
            tree.anchors_json,
            tree.index_sqlite,
            tree.speakers_snapshot,
            tree.lexicon_snapshot,
            tree.transcript_overview,
            *(target / chunk.filename for chunk in chunks),
        ],
        extra={
            "run": effective_run,
            "chunks": len(chunks),
            "turns": len(rendered),
            "segments": len(segments),
            "substitutions": dict(sorted(substitutions.explicit.items())),
            "substitutions_generated": dict(sorted(substitutions.generated.items())),
            "window_minutes": effective_window,
            "merge_gap_s": effective_gap,
            # The whole generated table, so every substitution a human did not
            # write down by hand can still be checked pair by pair after the fact.
            "morph_expansion": expansion.to_dict(),
        },
    )

    lines = [
        f"ok: {session_id} run {effective_run} — {len(chunks)} chunk(s), "
        f"{len(rendered)} turn(s), {len(segments)} segment(s)",
        f"  Transcript: {target}",
        f"  Anchors:    {tree.anchors_json}",
        f"  Index:      {tree.index_sqlite}",
    ]
    if substitutions.explicit:
        lines.append(
            "  Lexicon:    "
            + ", ".join(f"{term}×{count}" for term, count in sorted(substitutions.explicit.items()))
        )
    if substitutions.generated:
        lines.append(
            "  Morph:      "
            + ", ".join(
                f"{term}×{count}" for term, count in sorted(substitutions.generated.items())
            )
        )
    lines.extend(f"  warning: {message}" for message in warnings)

    return {
        "status": "ok",
        "session": session_id,
        "run": effective_run,
        "dataset_digest": recording.dataset_digest,
        "transcript_dir": str(target),
        "overview": str(tree.transcript_overview),
        "chunk_count": len(chunks),
        "chunks": chunk_payload,
        "turns": len(rendered),
        "segments": len(segments),
        "anchored_segments": len(anchors),
        "anchors": str(tree.anchors_json),
        "index": str(tree.index_sqlite),
        "snapshots": {
            "speakers": str(tree.speakers_snapshot),
            "speakers_present": speakers_present,
            "lexicon": str(tree.lexicon_snapshot),
            "lexicon_present": lexicon_present,
        },
        "substitutions": dict(sorted(substitutions.explicit.items())),
        "substitutions_generated": dict(sorted(substitutions.generated.items())),
        "substitutions_total": substitutions.total,
        "morph": {
            "digest": expansion.digest(),
            "versions": expansion.versions.to_dict(),
            "terms": len(expansion.terms),
            "pairs": sum(len(e.pairs) for e in expansion.terms.values()),
        },
        "unmapped_speakers": unmapped,
        "window_minutes": effective_window,
        "merge_gap_s": effective_gap,
        "warnings": warnings,
        "lines": lines,
        "next_steps": next_steps_for(
            "render", session_id=session_id, api_key_present=config.api_key_present
        ),
    }
