// Adapter generation. Every file written here is an OUTPUT: it carries a
// do-not-edit header and `verify` regenerates it into a temp tree and diffs.
// Change the canonical source or this generator — never the emitted file.

import fs from "node:fs";
import path from "node:path";

export const BANNER = "GENERATED by .agents/harness sync — do not edit. Source: ";

const collected = [];

function record(rel, contents) {
  collected.push({ rel, contents });
}

export function planned() {
  return collected.slice();
}

export function resetPlan() {
  collected.length = 0;
}

// ---------------------------------------------------------------------------
// helpers

function mdBanner(source) {
  return `<!-- ${BANNER}${source} -->\n`;
}

function shBanner(source) {
  return `# ${BANNER}${source}\n`;
}

function jsBanner(source) {
  return `// ${BANNER}${source}\n`;
}

function readBody(root, name) {
  return fs.readFileSync(path.join(root, ".agents/prompts", `${name}.md`), "utf8");
}

// Canonical bodies use pi's argument token. Rewrite it for Claude, including
// the backticked form used in prose. Anchored so a stray `$@` inside a shell
// example would also be caught — none exist today, and if one is ever added it
// should be escaped in the canonical body rather than silently mistranslated.
function claudeArgs(body) {
  return body.replace(/\$@/g, "$ARGUMENTS");
}

function yamlString(value) {
  // Always quote: descriptions contain colons, quotes and brackets.
  return JSON.stringify(String(value));
}

function tierModel(manifest, tier, harness) {
  if (!tier) return undefined;
  const entry = manifest.tiers?.[tier];
  if (!entry) throw new Error(`unknown model tier: ${tier}`);
  return entry[harness];
}

function effortLevel(manifest, effort, harness) {
  if (!effort) return undefined;
  const entry = manifest.effort?.[effort];
  if (!entry) throw new Error(`unknown effort level: ${effort}`);
  return entry[harness];
}

// ---------------------------------------------------------------------------
// skills: .claude/skills/<name> -> symlink into .agents/skills/<name>

export function skillNames(root) {
  const dir = path.join(root, ".agents/skills");
  return fs
    .readdirSync(dir, { withFileTypes: true })
    .filter((e) => e.isDirectory() && fs.existsSync(path.join(dir, e.name, "SKILL.md")))
    .map((e) => e.name)
    .sort();
}

export function syncClaudeSkills(root, { apply }) {
  const names = skillNames(root);
  const dir = path.join(root, ".claude/skills");
  if (apply) fs.mkdirSync(dir, { recursive: true });

  const results = [];
  for (const name of names) {
    const link = path.join(dir, name);
    const target = path.relative(dir, path.join(root, ".agents/skills", name));
    let state = "relinked";
    if (fs.existsSync(link) || fs.lstatSync(link, { throwIfNoEntry: false })) {
      const st = fs.lstatSync(link, { throwIfNoEntry: false });
      if (st && !st.isSymbolicLink()) {
        // Refuse to clobber a real directory — that would destroy hand-written
        // content that someone put in the wrong place.
        results.push({ name, state: "REFUSED (not a symlink)" });
        continue;
      }
      if (st && fs.readlinkSync(link) === target) state = "unchanged";
    } else {
      state = "created";
    }
    if (apply && state !== "unchanged") {
      // unlink, not rm: rmSync follows the symlink, so it throws EISDIR when
      // the link points at a directory (an absolute-path link from an older
      // sync) and silently succeeds without unlinking when the link dangles.
      try {
        fs.unlinkSync(link);
      } catch (error) {
        if (error.code !== "ENOENT") throw error;
      }
      fs.symlinkSync(target, link);
    }
    results.push({ name, state });
  }

  // Remove stale symlinks for skills that no longer exist.
  if (fs.existsSync(dir)) {
    for (const entry of fs.readdirSync(dir)) {
      if (names.includes(entry)) continue;
      const p = path.join(dir, entry);
      if (fs.lstatSync(p).isSymbolicLink()) {
        if (apply) {
          try {
            fs.unlinkSync(p);
          } catch (error) {
            if (error.code !== "ENOENT") throw error;
          }
        }
        results.push({ name: entry, state: "removed (stale)" });
      } else {
        // A real file/dir sitting where a generated symlink belongs. Never
        // delete it — say so, and let verify fail.
        results.push({ name: entry, state: "REFUSED (not a symlink, and not a known skill)" });
      }
    }
  }
  return results;
}

// ---------------------------------------------------------------------------
// prompts

// pi: the canonical body is CONCATENATED, not referenced. A "read and follow
// .agents/prompts/x.md" stub would downgrade pi from a guaranteed inlined body
// to an instruction the model may under-execute — a reliability regression on
// destructive commands like /cleanup.
export function genPiPrompts(root, manifest) {
  for (const p of manifest.prompt ?? []) {
    const fm = [
      "---",
      `name: ${p.name}`,
      `description: ${yamlString(p.description)}`,
    ];
    if (p.argument_hint) fm.push(`argument-hint: ${yamlString(p.argument_hint)}`);
    const effort = effortLevel(manifest, p.effort, "pi");
    if (effort) fm.push(`thinking: ${effort}`);
    const model = tierModel(manifest, p.tier, "pi");
    if (model) fm.push(`model: ${model}`);
    // pi's `skill:` is a guaranteed preload. Preserve it exactly.
    if (p.skill) fm.push(`skill: ${p.skill}`);
    fm.push("---", "");

    const body = readBody(root, p.name);
    record(`.pi/prompts/${p.name}.md`, fm.join("\n") + mdBanner(`.agents/prompts/${p.name}.md`) + "\n" + body);
  }
}

// Claude: the body is CONCATENATED, same as pi's, for two reasons.
//
//   1. `$@` is pi's argument token and Claude's is `$ARGUMENTS`. An @-import
//      inlines the canonical body *verbatim*, so the rewrite is impossible —
//      a literal `$@` would ship through to the model. That is not cosmetic:
//      /cleanup's body says "determine the intended scope from the user's
//      input" immediately after a line reading `User input: $@`.
//   2. `skill:` has no Claude equivalent, so we emit an explicit preload
//      preamble ahead of the body.
//
// Concatenating gives the same guaranteed-inline property @-import had, and
// lets the substitution actually happen.
export function genClaudeCommands(root, manifest) {
  for (const p of manifest.prompt ?? []) {
    const fm = ["---", `description: ${yamlString(p.description)}`];
    if (p.argument_hint) fm.push(`argument-hint: ${yamlString(p.argument_hint)}`);
    const model = tierModel(manifest, p.tier, "claude");
    if (model) fm.push(`model: ${model}`);
    fm.push("---", "");

    const lines = [fm.join("\n"), mdBanner(`.agents/prompts/${p.name}.md`), ""];
    if (p.skill) {
      lines.push(
        `**Before doing anything else, load the \`${p.skill}\` skill and follow it.**`,
        `It is not optional and it is not background reading: this command's`,
        `correctness depends on it.`,
        "",
      );
    }
    lines.push(claudeArgs(readBody(root, p.name)));
    record(`.claude/commands/${p.name}.md`, lines.join("\n"));
  }
}

// ---------------------------------------------------------------------------
// MCP

export function genMcpJson(root, manifest) {
  const servers = {};
  for (const m of manifest.mcp ?? []) {
    servers[m.name] = {
      // Claude silently DROPS entries without an explicit type.
      type: m.type,
      command: m.command,
      args: m.args,
    };
  }
  const doc = {
    _generated: `${BANNER}.agents/manifest.toml`,
    mcpServers: servers,
  };
  record(".mcp.json", JSON.stringify(doc, null, 2) + "\n");
}

// Codex has its own TOML adapter. Keep it generated from the same manifest as
// .mcp.json so the server name and hermetic launcher cannot drift.
export function genCodexConfig(root, manifest) {
  const lines = [shBanner(".agents/manifest.toml").trimEnd(), ""];
  for (const m of manifest.mcp ?? []) {
    lines.push(
      `[mcp_servers.${m.name}]`,
      `command = ${JSON.stringify(m.codex_command ?? m.command)}`,
      `args = ${JSON.stringify(m.codex_args ?? m.args)}`,
    );
    if (m.codex_startup_timeout_sec !== undefined) {
      lines.push(`startup_timeout_sec = ${Number(m.codex_startup_timeout_sec)}`);
    }
    if (m.codex_default_tools_approval_mode) {
      lines.push(
        `default_tools_approval_mode = ${JSON.stringify(m.codex_default_tools_approval_mode)}`,
      );
    }
    lines.push("");
  }
  record(".codex/config.toml", lines.join("\n"));
}

// ---------------------------------------------------------------------------
// Claude settings

export function genClaudeSettings(root, manifest) {
  const mcpNames = (manifest.mcp ?? []).map((m) => m.name);
  const binNames = [];
  for (const t of manifest.tool ?? []) for (const b of t.bin ?? []) binNames.push(b);
  binNames.push("qmd", "qmd-cpu");

  const settings = {
    _generated: `${BANNER}.agents/manifest.toml`,
    hooks: {
      // The env contract, applied before every Bash call. $CLAUDE_ENV_FILE is
      // supplied only to SessionStart/Setup/CwdChanged/FileChanged hooks.
      //
      // $CLAUDE_PROJECT_DIR must be expanded HERE, at hook time. Writing it
      // literally into the env file expands to empty inside the Bash tool's
      // shell — learned the hard way.
      //
      // SessionStart alone is sufficient: env.sh derives everything from
      // TTRPG_ROOT/BASH_SOURCE rather than the cwd, so changing directory
      // cannot invalidate the sourced snippet.
      // The env file is sourced by whatever shell the Bash tool uses — the
      // user's login shell. fish cannot source POSIX shell, so pick the right
      // file. (.agents/env.fish contains no duplicated logic; it transcribes
      // `TTRPG_ENV_DUMP=1 bash env.sh` and delegates qmd to .agents/bin.)
      //
      // TTRPG_ROOT is exported alongside, and that is load-bearing: Claude's
      // Bash cwd persists across calls, so after a single `cd /tmp` env.sh
      // would otherwise fall back to cwd/git discovery, declare /tmp the
      // project, and build a whole ghost skeleton there with the caches
      // repointed. $CLAUDE_PROJECT_DIR is already in hand — use it.
      //
      // $CLAUDE_PROJECT_DIR must be expanded HERE, at hook time; written
      // literally it expands to empty inside the Bash tool's shell.
      SessionStart: [
        {
          hooks: [
            {
              type: "command",
              command:
                'case "${SHELL##*/}" in ' +
                'fish) printf \'set -gx TTRPG_ROOT "%s"\\nsource "%s/.agents/env.fish"\\n\' "$CLAUDE_PROJECT_DIR" "$CLAUDE_PROJECT_DIR" >> "$CLAUDE_ENV_FILE" ;; ' +
                '*) printf \'export TTRPG_ROOT="%s"\\nsource "%s/.agents/env.sh"\\n\' "$CLAUDE_PROJECT_DIR" "$CLAUDE_PROJECT_DIR" >> "$CLAUDE_ENV_FILE" ;; ' +
                "esac",
            },
          ],
        },
      ],
    },
    enabledMcpjsonServers: mcpNames,
    permissions: {
      allow: [
        ...binNames.sort().map((b) => `Bash(.agents/bin/${b}:*)`),
        "Bash(.agents/harness:*)",
      ],
    },
  };
  record(".claude/settings.json", JSON.stringify(settings, null, 2) + "\n");
}

// ---------------------------------------------------------------------------
// CLAUDE.md — Claude does not load AGENTS.md on its own.

export function genClaudeMd(root, manifest) {
  const contract = manifest.project?.contract ?? "AGENTS.md";
  record(
    "CLAUDE.md",
    [
      mdBanner(".agents/manifest.toml"),
      "",
      `Claude Code does not load \`${contract}\` on its own, so this file imports it.`,
      `The project contract lives in \`${contract}\` — edit that, not this file.`,
      "",
      `@${contract}`,
      "",
    ].join("\n"),
  );
}

// ---------------------------------------------------------------------------
// creative-brainstorm chain: four artifacts from one spec

function candidateSchema(spec) {
  const props = {};
  for (const field of spec.candidateFields) {
    props[field] =
      field === "risks"
        ? { type: "array", minItems: 1, items: { type: "string" } }
        : { type: "string" };
  }
  return {
    type: "object",
    additionalProperties: false,
    required: ["candidates"],
    properties: {
      candidates: {
        type: "array",
        minItems: spec.candidatesMin,
        maxItems: spec.candidatesMax,
        items: {
          type: "object",
          additionalProperties: false,
          required: spec.candidateFields.slice(),
          properties: props,
        },
      },
    },
  };
}

function lensTask(spec, lens) {
  return [
    "CREATIVE BRIEF",
    "{task}",
    "",
    `ASSIGNED LENS — ${lens.title}`,
    `${lens.brief} Generate ${spec.candidatesMin}–${spec.candidatesMax} candidates and return only the required structured output.`,
  ].join("\n");
}

export function genChain(root, manifest) {
  for (const entry of manifest.chain ?? []) {
    const spec = JSON.parse(fs.readFileSync(path.join(root, entry.spec), "utf8"));
    const schema = candidateSchema(spec);

    // --- pi chain JSON ---
    const chain = {
      _generated: `${BANNER}${entry.spec}`,
      name: spec.name,
      description: spec.description,
      chain: [
        {
          phase: "Divergence",
          label: "Four creative lenses",
          parallel: spec.lenses.map((lens) => ({
            agent: spec.personas.ideator.name,
            as: lens.id,
            skill: false,
            reads: false,
            progress: false,
            task: lensTask(spec, lens),
            outputSchema: schema,
            acceptance: false,
          })),
          concurrency: spec.concurrency,
          failFast: false,
          worktree: false,
        },
        {
          agent: spec.personas.curator.name,
          phase: "Curation",
          label: "Diverse shortlist",
          skill: false,
          reads: false,
          progress: false,
          task: [
            "CREATIVE BRIEF",
            "{task}",
            "",
            ...spec.lenses.flatMap((lens) => [
              `ANONYMIZED CANDIDATE BATCH ${lens.id.replace(/^batch_/, "").toUpperCase()}`,
              `{outputs.${lens.id}}`,
              "",
            ]),
            spec.curatorTask,
          ].join("\n"),
          acceptance: false,
        },
      ],
    };
    record(`.pi/chains/${spec.name}.chain.json`, JSON.stringify(chain, null, 2) + "\n");

    // --- pi agent personas ---
    for (const persona of [spec.personas.ideator, spec.personas.curator]) {
      const fm = [
        "---",
        `name: ${persona.name}`,
        // Quoted: spec.json is hand-edited, and a description containing ": "
        // makes the generated frontmatter unparseable YAML.
        `description: ${yamlString(persona.description)}`,
        `model: ${tierModel(manifest, persona.tier, "pi")}`,
        `thinking: ${effortLevel(manifest, persona.effort, "pi")}`,
        // Preserve pi's exact tool contract.
        `tools: ${persona.structuredOutput ? "structured_output" : "none"}`,
        "extensions:",
        "systemPromptMode: replace",
        "inheritProjectContext: false",
        "inheritSkills: false",
        "defaultContext: fresh",
        "maxSubagentDepth: 0",
        "completionGuard: false",
        "---",
        "",
      ].join("\n");
      record(
        `.pi/agents/${persona.name}.md`,
        fm + mdBanner(entry.spec) + "\n" + persona.body + "\n",
      );
    }

    // --- Claude workflow ---
    // Prose contains {braces}; every embedded string goes through
    // JSON.stringify so the emitted JS cannot be corrupted by the content.
    const js = [
      jsBanner(entry.spec),
      "",
      "export const meta = {",
      `  name: ${JSON.stringify(spec.name)},`,
      `  description: ${JSON.stringify(spec.description)},`,
      "  phases: [",
      '    { title: "Divergence", detail: "four isolated lenses, in parallel" },',
      '    { title: "Curation", detail: "one curator over the anonymized pool" },',
      "  ],",
      "};",
      "",
      `const IDEATOR = ${JSON.stringify(spec.personas.ideator.body)};`,
      `const CURATOR = ${JSON.stringify(spec.personas.curator.body)};`,
      `const SCHEMA = ${JSON.stringify(schema, null, 2)};`,
      `const LENSES = ${JSON.stringify(
        spec.lenses.map((l) => ({ id: l.id, title: l.title, task: lensTask(spec, l) })),
        null,
        2,
      )};`,
      "",
      "// `args` is the creative brief. The main agent is expected to have gathered",
      "// and verified the relevant context already and to pass a self-contained brief.",
      "const brief = typeof args === \"string\" ? args : (args?.task ?? \"\");",
      "if (!brief.trim()) {",
      '  throw new Error("creative-brainstorm needs a self-contained brief as args");',
      "}",
      "",
      "phase(\"Divergence\");",
      "const batches = await parallel(",
      "  LENSES.map((lens) => () =>",
      "    agent(`${IDEATOR}\\n\\n${lens.task.replace(\"{task}\", brief)}`, {",
      "      label: `lens:${lens.id}`,",
      '      phase: "Divergence",',
      "      schema: SCHEMA,",
      `      effort: ${JSON.stringify(effortLevel(manifest, spec.personas.ideator.effort, "claude"))},`,
      "    }),",
      "  ),",
      ");",
      "",
      "// A barrier is correct here: the curator's whole job is cross-candidate",
      "// comparison, so it genuinely needs every lens's output at once.",
      "phase(\"Curation\");",
      "const pool = LENSES.map((lens, i) => {",
      "  const out = batches[i];",
      "  const label = lens.id.replace(/^batch_/, \"\").toUpperCase();",
      "  return `ANONYMIZED CANDIDATE BATCH ${label}\\n${JSON.stringify(out ?? { candidates: [] }, null, 2)}`;",
      "}).join(\"\\n\\n\");",
      "",
      "const shortlist = await agent(",
      "  [CURATOR, \"\", \"CREATIVE BRIEF\", brief, \"\", pool, \"\", " +
        JSON.stringify(spec.curatorTask) + "].join(\"\\n\"),",
      "  {",
      '    label: "curator",',
      '    phase: "Curation",',
      `    effort: ${JSON.stringify(effortLevel(manifest, spec.personas.curator.effort, "claude"))},`,
      "  },",
      ");",
      "",
      "return shortlist;",
      "",
    ].join("\n");
    record(`.claude/workflows/${spec.name}.js`, js);
  }
}

// ---------------------------------------------------------------------------

export function generateAll(root, manifest) {
  resetPlan();
  genPiPrompts(root, manifest);
  genClaudeCommands(root, manifest);
  genMcpJson(root, manifest);
  genCodexConfig(root, manifest);
  genClaudeSettings(root, manifest);
  genClaudeMd(root, manifest);
  genChain(root, manifest);
  return planned();
}

// Directories whose *entire* matching contents are generated. Anything here
// that the current plan does not produce is an orphan: a renamed or deleted
// prompt/chain otherwise leaves a working /npc command behind forever, and the
// drift check (plan -> disk) cannot see it because it only walks the plan.
const GENERATED_DIRS = [
  { dir: ".claude/commands", test: (f) => f.endsWith(".md") },
  { dir: ".claude/workflows", test: (f) => f.endsWith(".js") },
  { dir: ".pi/prompts", test: (f) => f.endsWith(".md") },
  { dir: ".pi/chains", test: (f) => f.endsWith(".chain.json") },
  { dir: ".pi/agents", test: (f) => f.startsWith("creative-") && f.endsWith(".md") },
];

export function orphanedArtifacts(root, plan) {
  const produced = new Set(plan.map((p) => p.rel));
  const orphans = [];
  for (const { dir, test } of GENERATED_DIRS) {
    const abs = path.join(root, dir);
    if (!fs.existsSync(abs) || !fs.statSync(abs).isDirectory()) continue;
    for (const f of fs.readdirSync(abs)) {
      if (!test(f)) continue;
      const rel = `${dir}/${f}`;
      if (!produced.has(rel)) orphans.push(rel);
    }
  }
  return orphans.sort();
}

export function writePlan(root, plan) {
  const written = [];
  for (const { rel, contents } of plan) {
    const abs = path.join(root, rel);
    fs.mkdirSync(path.dirname(abs), { recursive: true });
    const before = fs.existsSync(abs) ? fs.readFileSync(abs, "utf8") : null;
    if (before === contents) {
      written.push({ rel, state: "unchanged" });
      continue;
    }
    fs.writeFileSync(abs, contents);
    written.push({ rel, state: before === null ? "created" : "updated" });
  }
  return written;
}
